spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/rest_pos"
    username: adminz
    password: 123123
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){highlight} %highlight(%-5level) - %msg%n'
  level:
    root: ERROR
    com:
      hti:
        pos: DEBUG
      zaxxer: DEBUG
    org:
      springframework: INFO
