server:
  servlet:
    context-path: /
  port: ${PORT:9999}
spring:
  devtools:
    restart:
      exclude: "static/**,public/**"
    add-properties: true
  banner:
    location: "classpath:${spring.profiles.active}.banner.txt"
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        enable_lazy_load_no_trans: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
    rest:
      basePath: /api
  mvc:
    log-request-details: true
  security:
    user:
      name: adminz
      password: 123123
      roles: admin
logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: ERROR
    web: DEBUG
    com:
      zaxxer: DEBUG
      hti:
        pos: DEBUG
    org.springframework: INFO
swagger:
  apiInfo:
    contactEmail: ravuthz@gmail.com
    contactName: ravuthz@gmail.com
    contactUrl: http://github.com/ravuthz/user-management-api
    description: POS System REST API with Spring Boot + Spring Data JPA + Spring Data REST.
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    termOfServiceUrl: http://swagger.io/terms/
    title: POS System
    version: 1.0.0
  defaultKey:
    page: page
    size: size
    sort: sort
  defaultValue:
    page: 0
    size: 20
    sort: id,desc
management:
  endpoints:
    web:
      exposure:
        include: '*'