spring:
  datasource:
    ## PostgreSQL database
    url: "jdbc:postgresql://localhost:5432/rest_pos"
    username: adminz
    password: 123123
    ## Default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: ERROR
    web: DEBUG
    com:
      zaxxer: DEBUG
      hti:
        pos: DEBUG
    org.springframework: INFO