server:
  servlet:
    context-path: /
  port: ${PORT:9999}
spring:
  datasource:
    ## PostgreSQL database
    url: "jdbc:postgresql://localhost:5432/rest_pos"
    username: adminz
    password: 123123
    ## Default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      basePath: /api
logging:
  level:
    root: ERROR
    web: DEBUG
    com:
      zaxxer: DEBUG
      hti:
        pos: DEBUG
    org.springframework: INFO
swagger:
  apiInfo:
    contactEmail: ravuthz@gmail.com
    contactName: ravuthz@gmail.com
    contactUrl: http://github.com/ravuthz/user-management-api
    description: Users Management REST API with Spring Boot + Spring Data JPA + Spring Data REST + Spring Security + Spring Security JWT + Spring Security OAUTH 2.
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    termOfServiceUrl: http://swagger.io/terms/
    title: User Management API
    version: 1.0.0
  defaultKey:
    page: page
    size: size
    sort: sort
  defaultValue:
    page: 0
    size: 20
    sort: id,desc
management:
  endpoints:
    web:
      exposure:
        include: '*'