spring:
  banner:
    location: "classpath:test.banner.txt"
    image:
      location: "https://javacodehouse.com/assets/img/junit/junit.png"
      pixelmode: block
  datasource:
    url: "jdbc:postgresql://localhost:5432/rest_pos_test"
    username: adminz
    password: 123123
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  level:
    root: ERROR
